const string Syberia_ModPreffix = "[SYBERIA] ";
const bool Syberia_DebugMode = true;

void SybLog(string message)
{
	if (Syberia_DebugMode) Print(Syberia_ModPreffix + message);
}

enum SyberiaRPC {
    SYBRPC_RESPAWN_SCREEN_OPEN,
	SYBRPC_NEWCHAR_SCREEN_OPEN,
	SYBRPC_EQUIP_SCREEN_OPEN,
	SYBRPC_CREATENEWCHAR_REQUEST,
	SYBRPC_STARTGAME_REQUEST,
	SYBRPC_RESPAWN_REQUEST,
	SYBRPC_DELETECHAR_REQUEST
};

// VALUE - (SLEEPING_DEC_PER_SEC + SLEEPING_DEC_PER_INJURE_SEC) + (SLEEPING_INC_PER_UNCONSION_SEC + SLEEPING_INC_PER_SLEEPING_SEC)
const int NTFKEY_SLEEPING = 100;
const int SLEEPING_MAX_VALUE = 14000;
const int SLEEPING_DEC_PER_SEC = 1;
const bool SLEEPING_UNCONSION_ENABLED = false;
const int SLEEPING_INC_PER_UNCONSION_BOOST_VALUE = 5;
const int SLEEPING_INC_PER_UNCONSION_BOOST_TIME = 30;
const int SLEEPING_INC_PER_SLEEPING_SEC = 15;
const int SLEEPING_LEVEL_5 = 100;
const int SLEEPING_LEVEL_4 = 1000;
const int SLEEPING_LEVEL_3 = 5000;
const int SLEEPING_LEVEL_2 = 10000;