class BakedBeansCan_Opened;
class PeachesCan_Opened;
class TacticalBaconCan_Opened;
class SpaghettiCan_Opened;
class SardinesCan_Opened;
class TunaCan_Opened;
class DogFoodCan_Opened;
class CatFoodCan_Opened;
class PorkCan_Opened;
class Lunchmeat_Opened;
class UnknownFoodCan_Opened;
class Pajka_Opened;
class Pate_Opened;
class BrisketSpread_Opened;

class BakedBeansCan_OpenedRotten : BakedBeansCan_Opened {};
class PeachesCan_OpenedRotten : PeachesCan_Opened {};
class TacticalBaconCan_OpenedRotten : TacticalBaconCan_Opened {};
class SpaghettiCan_OpenedRotten : SpaghettiCan_Opened {};
class SardinesCan_OpenedRotten : SardinesCan_Opened {};
class TunaCan_OpenedRotten : TunaCan_Opened {};
class DogFoodCan_OpenedRotten : DogFoodCan_Opened {};
class CatFoodCan_OpenedRotten : CatFoodCan_Opened {};
class PorkCan_OpenedRotten : PorkCan_Opened {};
class Lunchmeat_OpenedRotten : Lunchmeat_Opened {};
class UnknownFoodCan_OpenedRotten : UnknownFoodCan_Opened {};
class Pajka_OpenedRotten : Pajka_Opened {};
class Pate_OpenedRotten : Pate_Opened {};
class BrisketSpread_OpenedRotten : BrisketSpread_Opened {};